declare module "lodash" {
  function head(array: number[]): number;
  // function hasIn(...): ...
  // function isBoolean(...): ...
  // function toString(...): ...
  // function split(...): ...
  // function hasPath(...): ...
  // function filter(...): ...
  // function every(...): ...
  // function map(...): ...
}
